/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Paùl Arias
 */
public class Preferencias extends javax.swing.JFrame {

    /**
     * Creates new form Presentacion
     */
    public Preferencias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnValidar = new javax.swing.JButton();
        btnHablo_Bastante = new javax.swing.JButton();
        btnNo_hablo_mucho = new javax.swing.JButton();
        btnHablo_Poco = new javax.swing.JButton();
        btnNo_fumo = new javax.swing.JButton();
        btnFumo_Poco = new javax.swing.JButton();
        btnFumo = new javax.swing.JButton();
        btnNo_Mascotas = new javax.swing.JButton();
        btnNo_Mucho_Masc = new javax.swing.JButton();
        btnMe_gustan = new javax.swing.JButton();
        btnNo_escucho_mus = new javax.swing.JButton();
        btnNo_me_disg_mus = new javax.swing.JButton();
        btnMe_gus_mus = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Preferencias de Viaje");

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setText("Conversación: ");

        jLabel3.setText("Fumar en el coche: ");

        jLabel4.setText("Mascotas: ");

        jLabel5.setText("Música: ");

        btnValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Validar.png"))); // NOI18N
        btnValidar.setBorder(null);
        btnValidar.setContentAreaFilled(false);
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnHablo_Bastante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hablo mucho.png"))); // NOI18N
        btnHablo_Bastante.setBorder(null);
        btnHablo_Bastante.setContentAreaFilled(false);

        btnNo_hablo_mucho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hablo poco.png"))); // NOI18N
        btnNo_hablo_mucho.setBorder(null);
        btnNo_hablo_mucho.setContentAreaFilled(false);
        btnNo_hablo_mucho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo_hablo_muchoActionPerformed(evt);
            }
        });

        btnHablo_Poco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/No hablo mucho.png"))); // NOI18N
        btnHablo_Poco.setBorder(null);
        btnHablo_Poco.setContentAreaFilled(false);
        btnHablo_Poco.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/No hablo mucho.png"))); // NOI18N
        btnHablo_Poco.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHablo_Poco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHablo_Poco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHablo_PocoActionPerformed(evt);
            }
        });

        btnNo_fumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/No fumo.png"))); // NOI18N
        btnNo_fumo.setBorder(null);
        btnNo_fumo.setContentAreaFilled(false);
        btnNo_fumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo_fumoActionPerformed(evt);
            }
        });

        btnFumo_Poco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fumo poco.png"))); // NOI18N
        btnFumo_Poco.setBorder(null);
        btnFumo_Poco.setContentAreaFilled(false);
        btnFumo_Poco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFumo_PocoActionPerformed(evt);
            }
        });

        btnFumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fumo.png"))); // NOI18N
        btnFumo.setBorder(null);
        btnFumo.setContentAreaFilled(false);

        btnNo_Mascotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/No mascotas.png"))); // NOI18N
        btnNo_Mascotas.setBorder(null);
        btnNo_Mascotas.setContentAreaFilled(false);

        btnNo_Mucho_Masc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/no me disgustan las mascotas.png"))); // NOI18N
        btnNo_Mucho_Masc.setBorder(null);
        btnNo_Mucho_Masc.setContentAreaFilled(false);

        btnMe_gustan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/me gustan las mascotas.png"))); // NOI18N
        btnMe_gustan.setBorder(null);
        btnMe_gustan.setContentAreaFilled(false);
        btnMe_gustan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMe_gustanActionPerformed(evt);
            }
        });

        btnNo_escucho_mus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Silencio.png"))); // NOI18N
        btnNo_escucho_mus.setBorder(null);
        btnNo_escucho_mus.setContentAreaFilled(false);

        btnNo_me_disg_mus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Escucho poco musica.png"))); // NOI18N
        btnNo_me_disg_mus.setBorder(null);
        btnNo_me_disg_mus.setContentAreaFilled(false);

        btnMe_gus_mus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Escucho musica.png"))); // NOI18N
        btnMe_gus_mus.setBorder(null);
        btnMe_gus_mus.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNo_fumo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHablo_Poco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNo_Mascotas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNo_escucho_mus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNo_me_disg_mus, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnNo_hablo_mucho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFumo_Poco, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnNo_Mucho_Masc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMe_gus_mus, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMe_gustan, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnFumo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnHablo_Bastante, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btnHablo_Bastante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNo_hablo_mucho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHablo_Poco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnFumo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnMe_gustan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFumo_Poco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnNo_fumo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnNo_Mucho_Masc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNo_Mascotas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnMe_gus_mus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNo_me_disg_mus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnNo_escucho_mus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnValidar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnNo_hablo_muchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo_hablo_muchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNo_hablo_muchoActionPerformed

    private void btnNo_fumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo_fumoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNo_fumoActionPerformed

    private void btnFumo_PocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFumo_PocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFumo_PocoActionPerformed

    private void btnMe_gustanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMe_gustanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMe_gustanActionPerformed

    private void btnHablo_PocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHablo_PocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHablo_PocoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preferencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preferencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFumo;
    private javax.swing.JButton btnFumo_Poco;
    private javax.swing.JButton btnHablo_Bastante;
    private javax.swing.JButton btnHablo_Poco;
    private javax.swing.JButton btnMe_gus_mus;
    private javax.swing.JButton btnMe_gustan;
    private javax.swing.JButton btnNo_Mascotas;
    private javax.swing.JButton btnNo_Mucho_Masc;
    private javax.swing.JButton btnNo_escucho_mus;
    private javax.swing.JButton btnNo_fumo;
    private javax.swing.JButton btnNo_hablo_mucho;
    private javax.swing.JButton btnNo_me_disg_mus;
    private javax.swing.JButton btnValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
